# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Product.create([
  { name: "The Beatles - Abbey Roac", price: 20.64, image_url: "https://images-na.ssl-images-amazon.com/images/I/81dUVKQDBEL._SL1200_.jpg", description: "The new Abbey Road release features the new stereo album mix, sourced directly from the original eight-track session tapes. To produce the mix, Giles Martin working with Sam Okell, was guided by the album’s original stereo mix supervised by his father, George Martin" },
  { name: "Michael Jackson - Thriller", price: 17.18, image_url: "https://images-na.ssl-images-amazon.com/images/I/81wfye0hsDL._SL1500_.jpg", description: "Michael Jackson - Thriller - LP Vinyl Album" },
  { name: "Pink Floyd - Dark Side of the Moon", price: 23.49, image_url: "https://images-na.ssl-images-amazon.com/images/I/61hw9WloObL._SL1500_.jpg", description: "PINK FLOYD / DARK SIDE OF MOON - Vinyl LP. The Dark Side of the Moon is the eighth album by the English rock band Pink Floyd. Originally released on 1 March 1973, on the label Harvest, it built on ideas explored in the band's earlier recordings and live shows, but departs from instrumental thematic by founding member Syd Barrett. The album explores themes including conflict, greed, the passage of time, and mental illness, the latter partly inspired by Barrett's deteriorating mental state." },
  { name: "Fleetwood Mac - Rumours", price: 23.50, image_url: "https://images-na.ssl-images-amazon.com/images/I/71HWqbh0BLL._SL1425_.jpg", description: "This 1975 multi-platimum album, Rumours became Fleetwood Mac's most celebrated album and one of the best-selling albums of all time. Certified at 18 million units by the RIAA" },
  { name: "J. Cole - Forest Hill Drive", price: 17.40, image_url: "https://images-na.ssl-images-amazon.com/images/I/71XstPLx8PL._SL1500_.jpg", description: "J. Cole - 2014 Forest Hills Drive 2LP Disc 1 Side 1   1. Intro   2. January 28th   3. Wet Dreamz   4. 03' Adolescence Disc 1 Side 2   1. A Tale of 2 Citiez   2. Fire Squad   3. St. Tropez Disc 2 Side 1   1. G.O.M.D.   2. No Role Modelz   3. Hello   4. Apparently Disc 2 Side 2   1. Love Yourz   2. Note to Self" },
  { name: "Tame Impala - Currents", price: 22.99, image_url: "https://images-na.ssl-images-amazon.com/images/I/91sqAJFwmJL._SL1400_.jpg", description: "Limited double vinyl LP pressing. 2015 release, the highly anticipated third full length album from the much loved Australian band. Currents is the follow up to 2012's Lonerism. Kevin Parker, the musician behind Tame Impala, explained that Currents is about the process of personal transformation. He said, It follows the progression of someone feeling like they are becoming something else." },
  { name: "Miles Davis - Kind Of Blue", price: 20.69, image_url: "https://images-na.ssl-images-amazon.com/images/I/81CP1j-zprL._SL1500_.jpg", description: "Miles said that he had wanted to draw closer to African and Gospel music as well as the blues, but admitted that he had failed in this intention. Nonetheless, he created his most indisputable masterpiece, containing two of the most popular standards of modern jazz, 'So What' and 'All Blues' On 'Flamenco Sketches,' Miles struck out to explore the harmonic realms of modal music, which he would radicalize ten years later. He also borrowed from Bill Evans, the principal creator of this album, the kind of blue that is reflected in 'Blue In Green.' For the last time, Miles called back the pianist who had just left his quintet, and it was Evans’ harmonic conceptions, inspired by early 20th century European music, that dominated Kind Of Blue.Wynton Kelly, the group’s new pianist, only appeared once, on 'Freddie Freeloader,”'and was stung sharply by this affront: the ultimate touch of bright red to heighten the depth of the blue." },
  { name: "Tyler, The Creator - IGOR", price: 22.43, image_url: "https://images-na.ssl-images-amazon.com/images/I/71udX8iRBsL._SL1200_.jpg", description: "Vinyl LP pressing in gatefold jacket. 2019 release. Igor is the fifth studio album by rapper Tyler, The Creator. Produced entirely by Tyler, the album follows the 2017 release of Flower Boy. It features guest appearances from Playboi Carti, Lil Uzi Vert, Solange, Kanye West, and Jerrod Carmichael, along with backing vocals from Santigold, Jessy Wilson, La Roux, CeeLo Green, Charlie Wilson, Slowthai, and Pharrell, among others."},
  { name: "Weezer - Blue Album", price: 12.98, image_url: "https://images-na.ssl-images-amazon.com/images/I/61%2BYFnKqzgL._SL1400_.jpg", description: "Weezer, with its simple blue cover featuring a group band shot, was not like anything most kids in 1994 had heard before, taking its nerdy cues from strange places the 1950s, comic books, Dungeons & Dragons, the Bible and producer Ric Ocasek, pop auteur of The Cars. Initially released without a single or much notice, the album's sales started slow but eventually reached triple platinum status, spending 78 weeks on the chart and peaking at No. 16 on the Billboard 200 albums chart." },
  { name: "Nirvana - Nevermind", price: 20.33, image_url: "https://images-na.ssl-images-amazon.com/images/I/71VZjASx2kL._SL1400_.jpg", description: "Limited 180gm vinyl pressing of this classic 1991 album from Kurt Cobain and the boys. Nevermind became a surprise success in late 1991, largely due to the popularity of its first single, "Smells Like Teen Spirit". By January 1992, it had replaced Michael Jackson's album Dangerous at #1 on the Billboard 200 chart. The album also produced three other successful singles: Come as You Are, Lithium, and In Bloom. The Recording Industry Association of America has certified the album Diamond (over 10 million copies shipped), and the album has sold over 30 million copies worldwide." },
  { name: "Adele - 21", price: 17.09, image_url: "https://images-na.ssl-images-amazon.com/images/I/71ipksWZcjL._SL1500_.jpg", description: "21 is the eagerly awaited sophomore album from British singer-songwriter Adele. Its the follow up to Adele s critically acclaimed, Grammy award winning debut album 19 (both named after her age at the time the songs were written)." },
  { name: "Kendrick Lamar - Good Kid, m.A.A.d City", price: 17.90, image_url: "https://images-na.ssl-images-amazon.com/images/I/51R0mNJpZbL.jpg", description: "Double vinyl LP pressing. 2012 release from the Compton-based Hip Hop artist. Currently signed to Top Dawg, Aftermath and lnterscope. Lamar is a member of Hip Hop supergroup Black Hippy, along with fellow West Coast rappers and label mates Jay Rock. Schoolboy Q and Ab-Soul. He first gained major attention after being mentioned by Dr. Dre resulting in a buzz for the, then upcoming. release of his fourth mixtape." },
  { name: "Tom Petty & the Heartbreakers - Greatest Hits", price: 25.98, image_url: "https://images-na.ssl-images-amazon.com/images/I/91xCpe6mIgL._SL1500_.jpg", description: "The album is the biggest selling in the band's illustrious catalog, with sales surpassing twelve million copies since its 1993 release. The album contains nineteen classics including American Girl, Refugee, Don't Come Around Here No More and many others. The collection also features the singles from Tom Petty's solo album Full Moon Fever including Free Fallin, I Won't Back Down and Runnin' Down A Dream." },
  { name: "Johnny Cash - The Essential Johnny Cash", price: 21.96, image_url: "https://images-na.ssl-images-amazon.com/images/I/817VZsCODgL._SL1500_.jpg", description: "2LP set with 28 golden period classic hits including all his signature tunes in a fully authorized, high quality package" },
  { name: "Pearl Jam - Ten", price: 14.49, image_url: "https://images-na.ssl-images-amazon.com/images/I/813p1x7Vc8L._SL1200_.jpg", description: "180g vinyl reissue. 2017 remaster of the 1991 grunge classic from original mix with original artwork!" },
  { name: "Bob Marley - Legend", price: 18.95, image_url: "https://images-na.ssl-images-amazon.com/images/I/71EFb-BEAeL._SL1400_.jpg", description: "Bob Marley & The Wailers - Legend Vinyl LP. Bob Marley & The Wailers - Legend Vinyl LPDisc 1Side 11: Is This Love2: No Woman, No Cry3: Could You Be Loved" },
])
